[[mgr.prepend_keymap]]
on = "b"
run = "plugin whoosh jump_by_key"
desc = "Bookmarks"

[[mgr.prepend_keymap]]
on = "B"
run = "plugin whoosh save_cwd"
desc = "Bookmark current directory"

[[mgr.prepend_keymap]]
on = "q"
run = ["quit --no-cwd-file"]
desc = "Quit without changing directory"

[[mgr.prepend_keymap]]
on = "Q"
run = ["quit"]
desc = "Quit and change directory"

[[mgr.prepend_keymap]]
on = "S"
run = "plugin fg -- rg"
desc = "Search file contents with highlighted preview"

[[mgr.prepend_keymap]]
on = ["g", "c"]
run = 'cd "%APPDATA%\\yazi\\config"'
desc = "Go to Yazi config"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[mgr.prepend_keymap]]
on = ":"
run = '''shell --block -- nu'''
desc = "Открыть Nushell"

[[mgr.prepend_keymap]]
on = "<C-o>"
run = '''shell --block -- nu -c "input listen --types [key] | ignore"'''
desc = "Показать экран терминала"

[[mgr.prepend_keymap]]
on  = "<C-k>"
run = "plugin parent-arrow -1"

[[mgr.prepend_keymap]]
on  = "<C-j>"
run = "plugin parent-arrow 1"

